# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

platform:
  - x64

install:
  - choco install firefox --version 57.0.4

  - "%PYTHON%\\python.exe -m pip install pip wheel --upgrade"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r tests/ci/requirements.txt"


build: off

before_test:
  - ps: Start-Process python tests/resources/httpserver/start.py

test_script:
  - "%PYTHON%\\python.exe -m nose tests.modules.selenium.test_python:TestRobotExecutor.test_hold -vvv --with-coverage --cover-inclusive"

after_test:
  - "coverage report -m"
  - "codecov"
